-- Database dictionary stored directly in PostgreSQL metadata.
-- Keep these comments aligned with docs/database.md when the schema changes.

COMMENT ON TABLE public.auth_users IS 'Login accounts and account-security state.';
COMMENT ON COLUMN public.auth_users.user_id IS 'Primary UUID of the login account.';
COMMENT ON COLUMN public.auth_users.email IS 'Original trimmed email address used for communication.';
COMMENT ON COLUMN public.auth_users.email_normalized IS 'Lowercase normalized email used for unique lookup.';
COMMENT ON COLUMN public.auth_users.password_hash IS 'One-way password hash; never contains a plaintext password.';
COMMENT ON COLUMN public.auth_users.status IS 'Account lifecycle state: PENDING, ACTIVE, SUSPENDED, or DISABLED.';
COMMENT ON COLUMN public.auth_users.email_verified_at IS 'Time at which ownership of the email address was verified.';
COMMENT ON COLUMN public.auth_users.invited_by_user_id IS 'Administrator who originally invited this account, when applicable.';
COMMENT ON COLUMN public.auth_users.invited_at IS 'Time at which the account invitation was issued.';
COMMENT ON COLUMN public.auth_users.last_login_at IS 'Time of the latest successful login.';
COMMENT ON COLUMN public.auth_users.failed_login_attempts IS 'Current consecutive failed-login counter used for account lockout.';
COMMENT ON COLUMN public.auth_users.locked_until IS 'Time until which login is temporarily blocked.';
COMMENT ON COLUMN public.auth_users.created_at IS 'Time at which the account row was created.';
COMMENT ON COLUMN public.auth_users.updated_at IS 'Time of the latest account-row update.';
COMMENT ON COLUMN public.auth_users.version IS 'Optimistic-lock version incremented on concurrent-safe updates.';

COMMENT ON TABLE public.participants IS 'Participant profile associated one-to-one with a login account.';
COMMENT ON COLUMN public.participants.participant_id IS 'Primary UUID of the participant profile.';
COMMENT ON COLUMN public.participants.user_id IS 'Login account that owns this participant profile.';
COMMENT ON COLUMN public.participants.first_name IS 'Participant given name.';
COMMENT ON COLUMN public.participants.last_name IS 'Participant family name.';
COMMENT ON COLUMN public.participants.phone_number IS 'Participant contact telephone number.';
COMMENT ON COLUMN public.participants.created_at IS 'Time at which the participant profile was created.';
COMMENT ON COLUMN public.participants.updated_at IS 'Time of the latest participant-profile update.';
COMMENT ON COLUMN public.participants.version IS 'Optimistic-lock version for profile updates.';

COMMENT ON TABLE public.auth_roles IS 'Named authorization roles and their access scope.';
COMMENT ON COLUMN public.auth_roles.role_id IS 'Primary UUID of the role.';
COMMENT ON COLUMN public.auth_roles.role_code IS 'Stable uppercase code used by authorization rules and tokens.';
COMMENT ON COLUMN public.auth_roles.role_name IS 'Human-readable role name.';
COMMENT ON COLUMN public.auth_roles.status IS 'Whether the role is ACTIVE or INACTIVE.';
COMMENT ON COLUMN public.auth_roles.created_at IS 'Time at which the role was created.';
COMMENT ON COLUMN public.auth_roles.updated_at IS 'Time of the latest role update.';
COMMENT ON COLUMN public.auth_roles.description IS 'Human-readable explanation of the role purpose.';
COMMENT ON COLUMN public.auth_roles.is_system IS 'True for protected built-in roles that cannot be removed or recoded.';
COMMENT ON COLUMN public.auth_roles.scope_type IS 'Data scope granted by the role: SELF, ASSIGNED_EVENTS, or GLOBAL.';

COMMENT ON TABLE public.auth_permissions IS 'Stable fine-grained permission catalogue.';
COMMENT ON COLUMN public.auth_permissions.permission_id IS 'Primary UUID of the permission.';
COMMENT ON COLUMN public.auth_permissions.permission_code IS 'Stable uppercase permission code checked by backend authorization.';
COMMENT ON COLUMN public.auth_permissions.description IS 'Human-readable description of the allowed operation.';
COMMENT ON COLUMN public.auth_permissions.created_at IS 'Time at which the permission was defined.';

COMMENT ON TABLE public.auth_role_permissions IS 'Many-to-many grants connecting roles to permissions.';
COMMENT ON COLUMN public.auth_role_permissions.role_id IS 'Role receiving the permission.';
COMMENT ON COLUMN public.auth_role_permissions.permission_id IS 'Permission granted to the role.';
COMMENT ON COLUMN public.auth_role_permissions.granted_at IS 'Time at which the permission was granted.';

COMMENT ON TABLE public.auth_user_roles IS 'Many-to-many role assignments for user accounts.';
COMMENT ON COLUMN public.auth_user_roles.user_id IS 'User account receiving the role.';
COMMENT ON COLUMN public.auth_user_roles.role_id IS 'Role assigned to the user account.';
COMMENT ON COLUMN public.auth_user_roles.assigned_by_user_id IS 'Administrator who made the assignment; null for system/bootstrap assignment.';
COMMENT ON COLUMN public.auth_user_roles.assigned_at IS 'Time at which the role was assigned.';

COMMENT ON TABLE public.auth_sessions IS 'Hashed refresh-token sessions and token-family rotation state.';
COMMENT ON COLUMN public.auth_sessions.session_id IS 'Primary UUID of the refresh session.';
COMMENT ON COLUMN public.auth_sessions.user_id IS 'Account that owns the session.';
COMMENT ON COLUMN public.auth_sessions.token_hash IS 'SHA-256 hash of the opaque refresh token.';
COMMENT ON COLUMN public.auth_sessions.token_family_id IS 'Stable family UUID shared by all rotations of one login session.';
COMMENT ON COLUMN public.auth_sessions.parent_session_id IS 'Previous session consumed to create this rotated session.';
COMMENT ON COLUMN public.auth_sessions.user_agent IS 'Truncated client User-Agent recorded for security review.';
COMMENT ON COLUMN public.auth_sessions.ip_address IS 'Client IP address observed when the session was issued.';
COMMENT ON COLUMN public.auth_sessions.expires_at IS 'Time after which the refresh session is invalid.';
COMMENT ON COLUMN public.auth_sessions.revoked_at IS 'Time at which the session was revoked.';
COMMENT ON COLUMN public.auth_sessions.revoked_reason IS 'Machine-readable or operational reason for revocation.';
COMMENT ON COLUMN public.auth_sessions.created_at IS 'Time at which the refresh session was created.';

COMMENT ON TABLE public.auth_login_attempts IS 'Security audit trail of successful and failed login attempts.';
COMMENT ON COLUMN public.auth_login_attempts.login_attempt_id IS 'Primary UUID of the login-attempt record.';
COMMENT ON COLUMN public.auth_login_attempts.user_id IS 'Resolved user account, null when the identifier did not match an account.';
COMMENT ON COLUMN public.auth_login_attempts.identifier_hash IS 'Non-reversible keyed hash of the submitted login identifier.';
COMMENT ON COLUMN public.auth_login_attempts.outcome IS 'Login result such as SUCCESS or FAILURE.';
COMMENT ON COLUMN public.auth_login_attempts.failure_reason IS 'Machine-readable failure category without exposing credentials.';
COMMENT ON COLUMN public.auth_login_attempts.ip_address IS 'Client IP address observed for the attempt.';
COMMENT ON COLUMN public.auth_login_attempts.user_agent IS 'Truncated client User-Agent observed for the attempt.';
COMMENT ON COLUMN public.auth_login_attempts.attempted_at IS 'Time at which the login attempt occurred.';

COMMENT ON TABLE public.auth_action_tokens IS 'Single-use hashed tokens for email verification and password reset.';
COMMENT ON COLUMN public.auth_action_tokens.action_token_id IS 'Primary UUID of the action token record.';
COMMENT ON COLUMN public.auth_action_tokens.user_id IS 'Account for which the action token was issued.';
COMMENT ON COLUMN public.auth_action_tokens.token_type IS 'Action performed by the token: EMAIL_VERIFICATION or PASSWORD_RESET.';
COMMENT ON COLUMN public.auth_action_tokens.token_hash IS 'SHA-256 hash of the raw token sent to the user.';
COMMENT ON COLUMN public.auth_action_tokens.expires_at IS 'Time after which the token cannot be consumed.';
COMMENT ON COLUMN public.auth_action_tokens.used_at IS 'Time at which the one-time token was consumed.';
COMMENT ON COLUMN public.auth_action_tokens.created_at IS 'Time at which the token was issued.';

COMMENT ON TABLE public.auth_invitations IS 'Administrator-issued invitations to join with a specific role.';
COMMENT ON COLUMN public.auth_invitations.invitation_id IS 'Primary UUID of the invitation.';
COMMENT ON COLUMN public.auth_invitations.invited_email IS 'Original trimmed email address receiving the invitation.';
COMMENT ON COLUMN public.auth_invitations.invited_email_normalized IS 'Generated lowercase email used for pending-invitation uniqueness.';
COMMENT ON COLUMN public.auth_invitations.role_id IS 'Role to assign when the invitation is accepted.';
COMMENT ON COLUMN public.auth_invitations.token_hash IS 'SHA-256 hash of the invitation token.';
COMMENT ON COLUMN public.auth_invitations.invited_by_user_id IS 'Administrator who created the invitation.';
COMMENT ON COLUMN public.auth_invitations.accepted_by_user_id IS 'Account that accepted the invitation.';
COMMENT ON COLUMN public.auth_invitations.status IS 'Invitation lifecycle state: PENDING, ACCEPTED, EXPIRED, or REVOKED.';
COMMENT ON COLUMN public.auth_invitations.expires_at IS 'Time after which the invitation cannot be accepted.';
COMMENT ON COLUMN public.auth_invitations.accepted_at IS 'Time at which the invitation was accepted.';
COMMENT ON COLUMN public.auth_invitations.created_at IS 'Time at which the invitation was created.';

COMMENT ON TABLE public.event_categories IS 'Reference catalogue used to classify events.';
COMMENT ON COLUMN public.event_categories.event_category_id IS 'Primary UUID of the event category.';
COMMENT ON COLUMN public.event_categories.code IS 'Stable uppercase category code.';
COMMENT ON COLUMN public.event_categories.name_th IS 'Thai display name.';
COMMENT ON COLUMN public.event_categories.name_en IS 'English display name.';
COMMENT ON COLUMN public.event_categories.description IS 'Optional category description.';
COMMENT ON COLUMN public.event_categories.is_active IS 'Whether the category is available for new and public event usage.';
COMMENT ON COLUMN public.event_categories.display_order IS 'Ascending UI display order.';
COMMENT ON COLUMN public.event_categories.created_at IS 'Time at which the category was created.';
COMMENT ON COLUMN public.event_categories.updated_at IS 'Time of the latest category update.';

COMMENT ON TABLE public.events IS 'Canonical event definition, schedule, registration policy, pricing, and lifecycle.';
COMMENT ON COLUMN public.events.event_id IS 'Primary UUID of the event.';
COMMENT ON COLUMN public.events.slug IS 'Unique URL-safe public event identifier.';
COMMENT ON COLUMN public.events.title IS 'Public event title.';
COMMENT ON COLUMN public.events.summary IS 'Short event summary for catalogue cards and search results.';
COMMENT ON COLUMN public.events.description IS 'Full public event description.';
COMMENT ON COLUMN public.events.event_category_id IS 'Optional category assigned to the event.';
COMMENT ON COLUMN public.events.created_by_user_id IS 'User account that created the event.';
COMMENT ON COLUMN public.events.status IS 'Event lifecycle state from draft through review, publication, cancellation, or completion.';
COMMENT ON COLUMN public.events.event_type IS 'Pricing type: FREE or PAID.';
COMMENT ON COLUMN public.events.price IS 'Authoritative registration price in the event currency.';
COMMENT ON COLUMN public.events.currency IS 'ISO 4217 three-letter currency code.';
COMMENT ON COLUMN public.events.refund_policy IS 'Policy text shown for paid-event cancellation and refund behavior.';
COMMENT ON COLUMN public.events.location_type IS 'Delivery mode: ONSITE, ONLINE, or HYBRID.';
COMMENT ON COLUMN public.events.location_name IS 'Venue name for onsite or hybrid events.';
COMMENT ON COLUMN public.events.address IS 'Venue postal address or arrival instructions.';
COMMENT ON COLUMN public.events.online_url IS 'Online attendance URL; access must be restricted when appropriate.';
COMMENT ON COLUMN public.events.image_url IS 'URL or object-storage reference for the event cover image.';
COMMENT ON COLUMN public.events.timezone IS 'IANA timezone used to interpret and display the event schedule.';
COMMENT ON COLUMN public.events.start_at IS 'Inclusive event start timestamp.';
COMMENT ON COLUMN public.events.end_at IS 'Event end timestamp.';
COMMENT ON COLUMN public.events.registration_start_at IS 'Time at which registration opens.';
COMMENT ON COLUMN public.events.registration_end_at IS 'Time at which registration closes.';
COMMENT ON COLUMN public.events.cancellation_deadline_at IS 'Latest time at which participant self-cancellation is permitted.';
COMMENT ON COLUMN public.events.maximum_participants IS 'Maximum number of confirmed/held participant seats.';
COMMENT ON COLUMN public.events.published_at IS 'Time at which the event was approved and made public.';
COMMENT ON COLUMN public.events.cancelled_at IS 'Time at which the event was cancelled.';
COMMENT ON COLUMN public.events.cancellation_reason IS 'Reason communicated/audited for event cancellation.';
COMMENT ON COLUMN public.events.created_at IS 'Time at which the event was created.';
COMMENT ON COLUMN public.events.updated_at IS 'Time of the latest event update.';
COMMENT ON COLUMN public.events.version IS 'Optimistic-lock version and review snapshot version.';
COMMENT ON COLUMN public.events.rules IS 'Participation and event rules shown to registrants.';
COMMENT ON COLUMN public.events.contact_email IS 'Contact email for questions about the event.';
COMMENT ON COLUMN public.events.eligibility IS 'Eligibility conditions for registration.';
COMMENT ON COLUMN public.events.allow_cancellation IS 'Whether participants may cancel before the configured deadline.';
COMMENT ON COLUMN public.events.show_remaining_seats IS 'Whether public responses may display remaining capacity.';

COMMENT ON TABLE public.event_admin_assignments IS 'Time-aware assignment of administrators to events.';
COMMENT ON COLUMN public.event_admin_assignments.event_admin_assignment_id IS 'Primary UUID of the assignment record.';
COMMENT ON COLUMN public.event_admin_assignments.event_id IS 'Event governed by the assignment.';
COMMENT ON COLUMN public.event_admin_assignments.admin_user_id IS 'Administrative user assigned to the event.';
COMMENT ON COLUMN public.event_admin_assignments.assignment_role IS 'Responsibility within the event: OWNER, EVENT_ADMIN, ORGANIZER, or COORDINATOR.';
COMMENT ON COLUMN public.event_admin_assignments.status IS 'Whether the assignment is ACTIVE or REMOVED.';
COMMENT ON COLUMN public.event_admin_assignments.assigned_by_user_id IS 'User who made the assignment; null for bootstrap/system assignment.';
COMMENT ON COLUMN public.event_admin_assignments.assigned_at IS 'Time at which the assignment became active.';
COMMENT ON COLUMN public.event_admin_assignments.removed_at IS 'Time at which the assignment was removed.';

COMMENT ON TABLE public.event_reviews IS 'Submission and decision history for publishing event versions.';
COMMENT ON COLUMN public.event_reviews.event_review_id IS 'Primary UUID of the review record.';
COMMENT ON COLUMN public.event_reviews.event_id IS 'Event submitted for review.';
COMMENT ON COLUMN public.event_reviews.event_version IS 'Optimistic event version captured when submitted.';
COMMENT ON COLUMN public.event_reviews.priority IS 'Review queue priority: STANDARD or HIGH.';
COMMENT ON COLUMN public.event_reviews.decision IS 'Review state: PENDING, APPROVED, REJECTED, or WITHDRAWN.';
COMMENT ON COLUMN public.event_reviews.submitted_by_user_id IS 'User who submitted the event for review.';
COMMENT ON COLUMN public.event_reviews.reviewed_by_user_id IS 'Super administrator who made the decision.';
COMMENT ON COLUMN public.event_reviews.comment IS 'Reviewer/submission comment explaining the decision or context.';
COMMENT ON COLUMN public.event_reviews.submitted_at IS 'Time at which review was requested.';
COMMENT ON COLUMN public.event_reviews.reviewed_at IS 'Time at which the review was decided or withdrawn.';

COMMENT ON TABLE public.event_change_requests IS 'Approval workflow for protected changes to a published event.';
COMMENT ON COLUMN public.event_change_requests.event_change_request_id IS 'Primary UUID of the change request.';
COMMENT ON COLUMN public.event_change_requests.event_id IS 'Published event whose fields are proposed to change.';
COMMENT ON COLUMN public.event_change_requests.requested_by_user_id IS 'Administrator requesting the changes.';
COMMENT ON COLUMN public.event_change_requests.status IS 'Request state: PENDING, APPROVED, REJECTED, or WITHDRAWN.';
COMMENT ON COLUMN public.event_change_requests.reason IS 'Requester explanation for the proposed changes.';
COMMENT ON COLUMN public.event_change_requests.reviewed_by_user_id IS 'Super administrator who made the decision.';
COMMENT ON COLUMN public.event_change_requests.review_comment IS 'Reviewer explanation for approval or rejection.';
COMMENT ON COLUMN public.event_change_requests.reviewed_at IS 'Time at which the request was decided or withdrawn.';
COMMENT ON COLUMN public.event_change_requests.created_at IS 'Time at which the request was created.';
COMMENT ON COLUMN public.event_change_requests.updated_at IS 'Time of the latest request update.';
COMMENT ON COLUMN public.event_change_requests.version IS 'Optimistic-lock version for concurrent decisions.';

COMMENT ON TABLE public.event_change_request_items IS 'Field-level old/new values belonging to an event change request.';
COMMENT ON COLUMN public.event_change_request_items.event_change_request_item_id IS 'Primary UUID of the changed-field record.';
COMMENT ON COLUMN public.event_change_request_items.event_change_request_id IS 'Parent event change request.';
COMMENT ON COLUMN public.event_change_request_items.field_name IS 'Canonical snake_case event field being changed.';
COMMENT ON COLUMN public.event_change_request_items.old_value IS 'JSON representation of the value before approval.';
COMMENT ON COLUMN public.event_change_request_items.new_value IS 'JSON representation of the proposed value.';
COMMENT ON COLUMN public.event_change_request_items.display_order IS 'Ascending display order for review UI.';

COMMENT ON TABLE public.registrations IS 'Participant registration snapshot, lifecycle, QR, and check-in state.';
COMMENT ON COLUMN public.registrations.registration_id IS 'Primary UUID of the registration.';
COMMENT ON COLUMN public.registrations.registration_number IS 'Unique human-readable registration reference.';
COMMENT ON COLUMN public.registrations.event_id IS 'Event for which the seat was registered.';
COMMENT ON COLUMN public.registrations.status IS 'Registration/payment/check-in lifecycle state.';
COMMENT ON COLUMN public.registrations.qr_token_hash IS 'Hash of an opaque check-in token when persistent QR tokens are used.';
COMMENT ON COLUMN public.registrations.registered_at IS 'Time at which registration was initiated.';
COMMENT ON COLUMN public.registrations.confirmed_at IS 'Time at which the registration became confirmed.';
COMMENT ON COLUMN public.registrations.cancelled_at IS 'Time at which the registration was cancelled.';
COMMENT ON COLUMN public.registrations.cancellation_reason IS 'User/admin reason for cancellation.';
COMMENT ON COLUMN public.registrations.checked_in_at IS 'Time at which event check-in completed.';
COMMENT ON COLUMN public.registrations.checked_in_by_user_id IS 'Administrator who performed the check-in.';
COMMENT ON COLUMN public.registrations.created_at IS 'Time at which the registration row was created.';
COMMENT ON COLUMN public.registrations.updated_at IS 'Time of the latest registration update.';
COMMENT ON COLUMN public.registrations.version IS 'Optimistic-lock version for registration state transitions.';
COMMENT ON COLUMN public.registrations.participant_id IS 'Participant profile that owns the registration.';
COMMENT ON COLUMN public.registrations.registered_by_user_id IS 'Authenticated account that submitted the registration.';
COMMENT ON COLUMN public.registrations.attendee_name IS 'Name snapshot captured at registration time.';
COMMENT ON COLUMN public.registrations.attendee_email IS 'Email snapshot captured at registration time.';
COMMENT ON COLUMN public.registrations.attendee_phone IS 'Telephone snapshot captured at registration time.';
COMMENT ON COLUMN public.registrations.consent_accepted_at IS 'Time at which required registration consent was accepted.';

COMMENT ON TABLE public.registration_status_history IS 'Append-only history of every registration status transition.';
COMMENT ON COLUMN public.registration_status_history.registration_status_history_id IS 'Primary UUID of the history entry.';
COMMENT ON COLUMN public.registration_status_history.registration_id IS 'Registration whose state changed.';
COMMENT ON COLUMN public.registration_status_history.from_status IS 'Previous status; null for the initial history entry.';
COMMENT ON COLUMN public.registration_status_history.to_status IS 'New registration status.';
COMMENT ON COLUMN public.registration_status_history.changed_by_user_id IS 'User responsible for the transition; null for system jobs/webhooks.';
COMMENT ON COLUMN public.registration_status_history.reason IS 'Human-readable or operational transition reason.';
COMMENT ON COLUMN public.registration_status_history.metadata IS 'Structured transition context that does not contain secrets.';
COMMENT ON COLUMN public.registration_status_history.changed_at IS 'Time at which the transition occurred.';

COMMENT ON TABLE public.seat_reservations IS 'Expiring capacity holds used to prevent overselling during registration/payment.';
COMMENT ON COLUMN public.seat_reservations.seat_reservation_id IS 'Primary UUID of the seat hold.';
COMMENT ON COLUMN public.seat_reservations.event_id IS 'Event whose capacity is held.';
COMMENT ON COLUMN public.seat_reservations.registration_id IS 'Registration that consumed the hold, when available.';
COMMENT ON COLUMN public.seat_reservations.reservation_token_hash IS 'Hash of the opaque token proving ownership of the hold.';
COMMENT ON COLUMN public.seat_reservations.status IS 'Hold state: ACTIVE, CONSUMED, EXPIRED, or CANCELLED.';
COMMENT ON COLUMN public.seat_reservations.quantity IS 'Number of seats held; currently constrained to one.';
COMMENT ON COLUMN public.seat_reservations.expires_at IS 'Time at which an unconsumed active hold expires.';
COMMENT ON COLUMN public.seat_reservations.consumed_at IS 'Time at which the hold became a registration/payment allocation.';
COMMENT ON COLUMN public.seat_reservations.cancelled_at IS 'Time at which the hold was explicitly cancelled.';
COMMENT ON COLUMN public.seat_reservations.created_at IS 'Time at which the hold was created.';
COMMENT ON COLUMN public.seat_reservations.updated_at IS 'Time of the latest hold update.';
COMMENT ON COLUMN public.seat_reservations.version IS 'Optimistic-lock version for hold state transitions.';
COMMENT ON COLUMN public.seat_reservations.participant_id IS 'Participant for whom the seat is held.';
COMMENT ON COLUMN public.seat_reservations.reserved_by_user_id IS 'Authenticated account that requested the hold.';

COMMENT ON TABLE public.payment_orders IS 'Provider-independent payment order linked to a registration and seat hold.';
COMMENT ON COLUMN public.payment_orders.payment_order_id IS 'Primary UUID of the payment order.';
COMMENT ON COLUMN public.payment_orders.order_number IS 'Unique human-readable payment order reference.';
COMMENT ON COLUMN public.payment_orders.idempotency_key IS 'Client/request key preventing duplicate order creation on retries.';
COMMENT ON COLUMN public.payment_orders.event_id IS 'Event being paid for.';
COMMENT ON COLUMN public.payment_orders.payer_user_id IS 'Authenticated account responsible for payment.';
COMMENT ON COLUMN public.payment_orders.registration_id IS 'Registration awaiting or associated with payment.';
COMMENT ON COLUMN public.payment_orders.seat_reservation_id IS 'Capacity hold protected while payment is pending.';
COMMENT ON COLUMN public.payment_orders.provider IS 'Configured payment provider code; NONE until a provider is integrated.';
COMMENT ON COLUMN public.payment_orders.provider_order_reference IS 'Unique order/reference returned by the payment provider.';
COMMENT ON COLUMN public.payment_orders.status IS 'Provider-independent payment lifecycle state.';
COMMENT ON COLUMN public.payment_orders.amount IS 'Authoritative amount copied from the event at order creation.';
COMMENT ON COLUMN public.payment_orders.currency IS 'ISO 4217 currency copied from the event at order creation.';
COMMENT ON COLUMN public.payment_orders.checkout_url IS 'Provider-hosted checkout or payment-instruction URL.';
COMMENT ON COLUMN public.payment_orders.expires_at IS 'Time after which the pending payment order expires.';
COMMENT ON COLUMN public.payment_orders.paid_at IS 'Time at which verified provider state confirmed payment.';
COMMENT ON COLUMN public.payment_orders.failed_at IS 'Time at which payment irrecoverably failed.';
COMMENT ON COLUMN public.payment_orders.expired_at IS 'Time at which the order was marked expired.';
COMMENT ON COLUMN public.payment_orders.cancelled_at IS 'Time at which payment was cancelled.';
COMMENT ON COLUMN public.payment_orders.refunded_at IS 'Time at which the order became fully refunded.';
COMMENT ON COLUMN public.payment_orders.failure_code IS 'Provider-independent or provider failure code.';
COMMENT ON COLUMN public.payment_orders.failure_message IS 'Sanitized payment failure description safe for operations.';
COMMENT ON COLUMN public.payment_orders.metadata IS 'Structured provider/order context excluding credentials and sensitive payment data.';
COMMENT ON COLUMN public.payment_orders.created_at IS 'Time at which the payment order was created.';
COMMENT ON COLUMN public.payment_orders.updated_at IS 'Time of the latest payment-order update.';
COMMENT ON COLUMN public.payment_orders.version IS 'Optimistic-lock version for payment state transitions.';

COMMENT ON TABLE public.audit_logs IS 'Append-only administrative and security audit events.';
COMMENT ON COLUMN public.audit_logs.audit_log_id IS 'Primary UUID of the audit event.';
COMMENT ON COLUMN public.audit_logs.actor_user_id IS 'Authenticated actor; null for system/background activity.';
COMMENT ON COLUMN public.audit_logs.action IS 'Stable uppercase action code.';
COMMENT ON COLUMN public.audit_logs.target_type IS 'Stable uppercase type of the affected resource.';
COMMENT ON COLUMN public.audit_logs.target_id IS 'UUID of the affected resource when one exists.';
COMMENT ON COLUMN public.audit_logs.target_label IS 'Human-readable target snapshot for later investigation.';
COMMENT ON COLUMN public.audit_logs.outcome IS 'Whether the audited action succeeded or failed.';
COMMENT ON COLUMN public.audit_logs.metadata IS 'Structured non-secret context describing the action.';
COMMENT ON COLUMN public.audit_logs.ip_address IS 'Client IP address associated with the action.';
COMMENT ON COLUMN public.audit_logs.user_agent IS 'Truncated client User-Agent associated with the action.';
COMMENT ON COLUMN public.audit_logs.request_id IS 'Correlation UUID joining the audit event to application logs.';
COMMENT ON COLUMN public.audit_logs.created_at IS 'Time at which the audited action occurred.';
